name: .NET

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Find branch name
      id: extract-branch-name
      run: |
        if [ $GITHUB_EVENT_NAME == 'pull_request' ]; then
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})
        else
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        fi

        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "Extracted branch name: $BRANCH_NAME"

    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_NAME }}     
      
    - name: Commit Lint
      uses: wagoid/commitlint-github-action@master
      with:
        firstParent: false
        failOnWarnings: true
    
    - name: Get changed files using defaults
      id: changed-files
      uses: tj-actions/changed-files@v6.3
      with:
        fetch-depth: 2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    # - name: Setup SonarScanner
    #   run: dotnet tool install --global dotnet-sonarscanner
      
    # - name: Setup Report Generator
    #   run: dotnet tool install --global dotnet-reportgenerator-globaltool
      
    # - name: Setup Java
    #   run: |
    #     sudo update-alternatives --query java
    #     sudo update-alternatives --auto java
    #     export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
    #     export PATH=$PATH:$JAVA_HOME
        
    # - name: MongoDB in GitHub Actions
    #   uses: supercharge/mongodb-github-action@1.6.0
    #   with:
    #     mongodb-version: '4.4'
        
    # - name: SonarScanner analysis begin
    #   run: dotnet sonarscanner begin /k:<TBD> /v:$BUILD_VERSION /o:<TBD> /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=<TBD> /d:sonar.coverage.exclusions="tests/*Tests/**" /d:sonar.coverageReportPaths="../../coverage-outputs/SonarQube.xml" /d:sonar.branch.name=$BRANCH_NAME
      
    - name: Restore dependencies
      run: dotnet restore src/KafkaFlow.Retry.sln
      
    - name: Build
      run: dotnet build --no-restore -c Release src/KafkaFlow.Retry.sln
      
    - name: Test
      run: dotnet test --no-build  -c Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"../../coverage-outputs" -m:1 src/KafkaFlow.Retry.sln
      
    # - name: Merge coverage results
    #   run: |
    #     reportgenerator -reports:"../../coverage-outputs/**/*.xml" -targetdir:"../../coverage-outputs" -reporttypes:SonarQube
    #     rm -rfv ../../coverage-outputs/*/
    #     ls -la ../../coverage-outputs
        
    # - name: SonarScanner analysis end
    #   run: dotnet sonarscanner end /d:sonar.login=8f9e9412fb5ebcf5ea6f9a6b285b288e4645f866
      
    - name: Pack KafkaFlow.Retry
      if: contains(steps.changed-files.outputs.all_modified_files, 'src/KafkaFlow.Retry/')
      run: dotnet pack src/KafkaFlow.Retry/KafkaFlow.Retry.csproj --no-build -c Release --include-symbols
      
    - name: Pack KafkaFlow.Retry.API
      if: contains(steps.changed-files.outputs.all_modified_files, 'src/KafkaFlow.Retry.API/')
      run: dotnet pack src/KafkaFlow.Retry.API/KafkaFlow.Retry.API.csproj --no-build -c Release --include-symbols
      
    - name: Pack KafkaFlow.Retry.SqlServer
      if: contains(steps.changed-files.outputs.all_modified_files, 'src/KafkaFlow.Retry.SqlServer/')
      run: dotnet pack src/KafkaFlow.Retry.SqlServer/KafkaFlow.Retry.SqlServer.csproj --no-build -c Release --include-symbols
      
    - name: Pack KafkaFlow.Retry.MongoDb
      if: contains(steps.changed-files.outputs.all_modified_files, 'src/KafkaFlow.Retry.MongoDb/')
      run: dotnet pack src/KafkaFlow.Retry.MongoDb/KafkaFlow.Retry.MongoDb.csproj --no-build -c Release --include-symbols
      
    - name: Verify Changed files
      if: contains(github.ref, 'master')
      uses: tj-actions/verify-changed-files@v6.2
      id: verify-changed-files
      with:
        files: .nupkg
        
    # - name: Publish NuGet packages
    #   if: contains(github.ref, 'master') && steps.verify-changed-files.outputs.files_changed == 'true'
    #   uses: dansiegel/publish-nuget@v1.01
    #   with:
    #     filename: '**/*.nupkg'
    #     apiKey: ${{ secrets.NUGET_API_KEY }}